<a href="https://colab.research.google.com/github/devabhinavraj/insurance-purchase-prediction/blob/main/Binary_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
from google.colab import files

uploaded = files.upload()

Saving insurance_dataset.csv to insurance_dataset.csv

In [3]:
df = pd.read_csv("insurance_dataset.csv")
df

    age  affordability  have_insurance
0    22              1               0
1    25              0               0
2    47              1               1
3    52              0               0
4    46              1               1
5    56              1               1
6    55              0               0
7    60              0               1
8    62              1               1
9    61              1               1
10   18              1               0
11   28              1               0
12   27              0               1

In [4]:
X = df[["age" , "affordability"]]
Y = df["have_insurance"]
X

    age  affordability
0    22              1
1    25              0
2    47              1
3    52              0
4    46              1
5    56              1
6    55              0
7    60              0
8    62              1
9    61              1
10   18              1
11   28              1
12   27              0

In [5]:
Y

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    0
11    0
12    1
Name: have_insurance, dtype: int64

**SPLIT THE DATA**

In [6]:
x_train , x_test , y_train, y_test =  train_test_split(
    X,
    Y,
    test_size = 0.2,
    random_state = 42

)

In [12]:
model = LogisticRegression()
model.fit(x_test,y_test)
pred = model.predict([[22,0]])
print("Prediction:",pred)

Prediction: [0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [13]:
prob = model.predict_proba([[22,0]])
print("Probability:",prob)

Probability: [[0.99872062 0.00127938]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(